### PR TITLE
Use EE type in NewObject

### PR DESCRIPTION
**Pull request by drcjt**
Modify NewObject to take EETypePtr instead of size and to work out size from the EEType.
Created temp version of existing NewObject for use in NewString and readline - this will be removed when these are updated to take EETypePtr too

### CODE REVIEW

**Comment by drcjt** [comment]
Next steps for #236

**Comment by tgiphil** [comment]
Doesn't the compiler already know the type size; if so, this is faster and requires less code than looking it up at runtime.

**Comment by drcjt** [comment]
@tgiphil Thanks for the comment - Yes for allocation the compiler already knows the type size - I'm leaning towards passing both the size and the EETypePtr to NewObject which will avoid the lookup for the size but also allow the Object.m_pEEType field to be initialised.

**Comment by tgiphil** [comment]
Great! In our .NET compiler (https://www.mosa-project.org/), we pass both the size and pointer to the method table.

Do you have a discord or slack channel for this project?

**Comment by drcjt** [comment]
@tgiphil The MOSA project looks really interesting. I haven't setup a discord or slack for CSharp-80 currently.

**Pull request merged**
